name: 'Install macOS brew dependencies'
description: 'Install all brew dependencies given the family tree. This is a poor mans version of package manager until it gets mac support'
author: 'Barret Schloerke'
inputs:
  extra-packages:
    default: ""
    description: String of extra packages
    required: false
runs:
  using: "composite"
  steps:
    - name: Brew dependencies
      shell: Rscript {0}
      run: |
        if (identical(Sys.getenv("RUNNER_OS", "NOT MAC"), "macOS")) {
          pkg_deps <- pak::local_dev_deps(dependencies = TRUE)$packages
          has <- function(pkgs) {
            if (any(pkgs %in% pkg_deps)) return(TRUE)
            for (pkg in pkgs) {
              if (grepl(pkg, "${{ inputs.extra-packages }}", fixed = TRUE)) return(TRUE)
            }
            FALSE
          }
          if (has("Cairo")) {
            system("brew install --cask xquartz && brew install cairo")
          }
          if (has("textshaping")) {
            system("brew install harfbuzz fribidi")
          }
        }
