name: 'Does nothing'
description: 'Performs a no-op'
author: 'Barret Schloerke'
inputs:
  name:
    description: Name of locally defined action to run. Will execute `./github/actions/NAME/action.yaml`
    required: true
runs:
  using: "composite"
  steps:
    - name: Find local action
      id: local-action
      shell: bash
      run: |
        FILE=".github/actions/${{ inputs.name }}/action.yaml"
        if [ -f "$FILE" ]; then
          echo "::set-output name=to-run::$FILE"
        else
          echo "::set-output name=to-run::rstudio/shinycoreci/.github/actions-internal/no-op@v1"
        fi
    - name: Run local-pkgdown action
      uses: ${{ steps.local-action.outputs.to-run }}
