name: 'Run a locally defined R script'
description: 'Runs a locally defined script if it exists. Ex: ./.github/shinycoreci-steps/NAME.R'
author: 'Barret Schloerke'
inputs:
  name:
    description: Name of script to use
    required: false
runs:
  using: "composite"
  steps:
    - name: Run script
      shell: bash
      run: |
        if [ -f ".github/shinycoreci-steps/${{ inputs.name }}.sh" ]; then
          . ".github/shinycoreci-steps/${{ inputs.name }}.sh"
        fi
        if [ -f ".github/shinycoreci-steps/${{ inputs.name }}.R" ]; then
          Rscript -e "source('.github/shinycoreci-steps/${{ inputs.name }}.R', echo = TRUE)"
        fi
