on:
  workflow_call:
    inputs:
      extra-packages:
        type: string
        default: ""
        required: false
      cache-version:
        type: string
        default: "3"
        required: false
      pandoc-version:
        type: string
        default: "2.7.3"
        required: false
      check-title:
        type: boolean
        default: true
        required: false
    secrets:
      NETLIFY_AUTH_TOKEN:
        required: false
      NETLIFY_SITE_ID:
        required: false
name: pkgdown

jobs:
  pkgdown:

    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ github.token }}

    steps:
      - uses: actions/checkout@v2

      - uses: rstudio/shinycoreci/.github/actions/install-r-package@v1
        with:
          pandoc-version: ${{ inputs.pandoc-version }}
          cache-version: ${{ inputs.cache-version }}
          needs: website
          extra-packages: |
            pkgdown
            ${{ inputs.extra-packages }}

      - name: Run local before-build-site step
        uses: rstudio/shinycoreci/.github/actions-internal/run-local-step@v1
        with:
          name: before-build-site

      - name: Verify reference (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          if ("${{inputs.check-title}}" == "false") options(rmarkdown.html_vignette.check_title = FALSE)
          pkgdown::build_site(new_process = FALSE)
          if (!require("testthat")) pak::pkg_install("testthat")
          testthat::expect_warning(
            pkgdown::build_reference_index(),
            NA
          )

      - name: Setup git (GitHub - push)
        if: github.event_name == 'push' && env.NETLIFY_SITE_ID == ''
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Build and deploy pkgdown site (GitHub - push)
        if: github.event_name == 'push' && env.NETLIFY_SITE_ID == ''
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        shell: Rscript {0}
        run: |
          if ("${{inputs.check-title}}" == "false") options(rmarkdown.html_vignette.check_title = FALSE)
          pkgdown::deploy_to_branch(new_process = FALSE)


      - name: Build pkgdown site (Netlify - push)
        if: github.event_name == 'push' && env.NETLIFY_SITE_ID != ''
        run: pkgdown::build_site(new_process = FALSE)
        shell: Rscript {0}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Deploy to Netlify (Netlify - push)
        if: github.event_name == 'push' && env.NETLIFY_SITE_ID != ''
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: 'reference'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.head_commit.message }} (${{ github.sha }})'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
